[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
objects = {path = "../objects"}
wasm-bindgen = "0.2.90"
websocket = "0.27.0"
