[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objects = {path = "../objects"}
serde-binary = "0.5.0"
websocket = "0.27.0"

